import { DirectorStyle } from '../types';

export const DIRECTOR_PRESETS: Record<string, DirectorStyle> = {
  noir_cold: {
    id: 'noir_cold',
    name: 'Film Noir & Melancholy',
    tagline: 'Rain-slicked asphalt, shadows, and cigarette smoke.',
    description: 'Cold cyan and midnight blue tones, heavy film grain, persistent rain downpour, and slow, mournful synthetic brass/drones.',
    colorPalette: {
      background: '#06080d',
      ambientLight: '#162235',
      accentColor: '#e5b869',
      textPrimary: '#edf2f7',
      textSecondary: '#718096',
      letterboxColor: '#000000',
    },
    grainIntensity: 0.09,
    vignetteStrength: 0.85,
    particleType: 'rain',
    particleIntensity: 0.9,
    lightingPace: 'slow',
    audioStyle: 'noir_drone',
    pacingMultiplier: 1.1,
  },

  minimal_a24: {
    id: 'minimal_a24',
    name: 'A24 Minimalist',
    tagline: 'Restrained, stark, and hyper-focused.',
    description: 'Subdued monochromes, ultra-fine 35mm grain, breathless room tone silence, and stark typography designed for maximum dramatic tension.',
    colorPalette: {
      background: '#090a0c',
      ambientLight: '#181a20',
      accentColor: '#d4d4d8',
      textPrimary: '#f4f4f5',
      textSecondary: '#71717a',
      letterboxColor: '#000000',
    },
    grainIntensity: 0.04,
    vignetteStrength: 0.5,
    particleType: 'dust',
    particleIntensity: 0.25,
    lightingPace: 'slow',
    audioStyle: 'ambient_minimal',
    pacingMultiplier: 1.15,
  },

  dreamlike_ethereal: {
    id: 'dreamlike_ethereal',
    name: 'Dreamlike & Ethereal',
    tagline: 'Soft bloom, floating memories, and twilight haze.',
    description: 'Deep violet and golden hour warmth, floating luminescence, slow camera drifts, and shimmering harmonic reverb soundscapes.',
    colorPalette: {
      background: '#0b0814',
      ambientLight: '#281c3d',
      accentColor: '#fcd34d',
      textPrimary: '#faf5ff',
      textSecondary: '#a78bfa',
      letterboxColor: '#000000',
    },
    grainIntensity: 0.03,
    vignetteStrength: 0.65,
    particleType: 'dust',
    particleIntensity: 0.7,
    lightingPace: 'slow',
    audioStyle: 'lofi_melancholy',
    pacingMultiplier: 1.25,
  },

  cyberpunk_neon: {
    id: 'cyberpunk_neon',
    name: 'Cyberpunk Neon',
    tagline: 'Electric rain, neon flares, and high-frequency tension.',
    description: 'Wet asphalt black with electric cyan and magenta reflections, sharp neon rain streaks, scanline grit, and pulse-driven synthesizer drones.',
    colorPalette: {
      background: '#05070a',
      ambientLight: '#0d1e2e',
      accentColor: '#06b6d4',
      textPrimary: '#f8fafc',
      textSecondary: '#38bdf8',
      letterboxColor: '#000000',
    },
    grainIntensity: 0.07,
    vignetteStrength: 0.75,
    particleType: 'neon',
    particleIntensity: 0.85,
    lightingPace: 'fast',
    audioStyle: 'cyber_synth',
    pacingMultiplier: 0.9,
  },

  cinematic_realism: {
    id: 'cinematic_realism',
    name: 'Cinematic Realism',
    tagline: 'Balanced natural lighting and organic acoustics.',
    description: 'Natural contrast, atmospheric depth based on scene time-of-day, subtle environmental audio, and balanced Hollywood pacing.',
    colorPalette: {
      background: '#0a0c10',
      ambientLight: '#1c222d',
      accentColor: '#e5b869',
      textPrimary: '#f1f5f9',
      textSecondary: '#94a3b8',
      letterboxColor: '#000000',
    },
    grainIntensity: 0.05,
    vignetteStrength: 0.6,
    particleType: 'rain',
    particleIntensity: 0.5,
    lightingPace: 'medium',
    audioStyle: 'lofi_melancholy',
    pacingMultiplier: 1.0,
  },
};

export const DEFAULT_DIRECTOR_STYLE = DIRECTOR_PRESETS.noir_cold;
